alias nix-del="nix-collect-garbage -d --delete-older-than 10d"
alias nix-bld='sudo nixos-rebuild switch --flake'
alias nix-upd='nix flake update'

alias kde-rst='systemctl --user restart plasma-plasmashell'
alias gi="git init && git add . && git commit -m 'Initial Commit'"
